name       : openra
version    : '20171014'
release    : 7
source     :
    - https://github.com/OpenRA/OpenRA/archive/release-20171014.tar.gz : ea8a6c38f22c3432bd173c15e3f3d96a7bb47c39f73db5aa5ab6df7e6980ed5a
license    : GPL-3.0
component  : games.strategy
summary    : A Libre/Free Real Time Strategy game engine supporting early Westwood classics
description: |
    A Libre/Free Real Time Strategy game engine supporting early Westwood classics
networking : yes
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lua-5.1)
    - pkgconfig(mono)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - zenity
rundeps    :
    - libgdiplus
    - lua51
    - mesalib
    - mono
    - openal-soft
    - sdl2-gfx
    - sdl2-image
    - sdl2-mixer
    - sdl2-net
    - sdl2-ttf
    - zenity
setup      : |
    sed -i "s|^VERSION.*$|VERSION = release-$version|" Makefile
build      : |
    %make DEBUG=false dependencies
    %make DEBUG=false version
    %make DEBUG=false
install    : |
    %make_install DEBUG=false prefix=/usr gameinstalldir=/usr/share/openra
    %make install-linux-shortcuts DEBUG=false DESTDIR=$installdir prefix=/usr gameinstalldir=/usr/share/openra
