name       : openra
version    : '20200503'
release    : 16
source     :
    - https://github.com/OpenRA/OpenRA/archive/release-20200503.tar.gz : 11ee0aa738c6e7fc4f39ab23f029a280a29530e28096c7da78eb12b12f1a854f
license    : GPL-3.0-or-later
component  : games.strategy
summary    : A Libre/Free Real Time Strategy game engine supporting early Westwood classics
description: |
    A Libre/Free Real Time Strategy game engine supporting early Westwood classics
networking : yes
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lua-5.1)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - mono-msbuild
    - xdg-utils
    - zenity
rundeps    :
    - libgdiplus
    - lua51
    - mesalib
    - mono
    - openal-soft
    - sdl2-gfx
    - sdl2-image
    - sdl2-mixer
    - sdl2-net
    - sdl2-ttf
    - xdg-utils
    - zenity
environment: |
    unset version
setup      : |
    cert-sync --user /etc/ssl/certs/ca-certificates.crt
    sed -i "s|^VERSION.*$|VERSION = release-%version%|" Makefile
build      : |
    %make DEBUG=false dependencies
    %make DEBUG=false version
    %make DEBUG=false
install    : |
    %make_install DEBUG=false prefix=/usr gameinstalldir=/usr/share/openra
    %make install-man-page DEBUG=false DESTDIR=$installdir prefix=/usr gameinstalldir=/usr/share/openra
    %make install-linux-shortcuts DEBUG=false DESTDIR=$installdir prefix=/usr gameinstalldir=/usr/share/openra
    %make install-linux-mime DEBUG=false DESTDIR=$installdir prefix=/usr gameinstalldir=/usr/share/openra
    %make install-linux-appdata DEBUG=false DESTDIR=$installdir prefix=/usr gameinstalldir=/usr/share/openra
