name       : openra
version    : '20180218'
release    : 8
source     :
    - https://github.com/OpenRA/OpenRA/archive/release-20180218.tar.gz : 8f8979f2124accea85e80e00e95573e82a46f0aa11f31d3167bf5f99a8df6ebc
license    : GPL-3.0
component  : games.strategy
summary    : A Libre/Free Real Time Strategy game engine supporting early Westwood classics
description: |
    A Libre/Free Real Time Strategy game engine supporting early Westwood classics
networking : yes
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lua-5.1)
    - pkgconfig(mono)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - zenity
rundeps    :
    - libgdiplus
    - lua51
    - mesalib
    - mono
    - openal-soft
    - sdl2-gfx
    - sdl2-image
    - sdl2-mixer
    - sdl2-net
    - sdl2-ttf
    - zenity
setup      : |
    sed -i "s|^VERSION.*$|VERSION = release-$version|" Makefile
build      : |
    %make DEBUG=false dependencies
    %make DEBUG=false version
    %make DEBUG=false
install    : |
    %make_install DEBUG=false prefix=/usr gameinstalldir=/usr/share/openra
    %make install-linux-shortcuts DEBUG=false DESTDIR=$installdir prefix=/usr gameinstalldir=/usr/share/openra
