name       : openra
version    : '20181215'
release    : 12
source     :
    - https://github.com/OpenRA/OpenRA/archive/release-20181215.tar.gz : 8214a8945c6667899a0d5f8956718b8e163d0184989d7c50972cc11c4f8311f2
license    : GPL-3.0-or-later
component  : games.strategy
summary    : A Libre/Free Real Time Strategy game engine supporting early Westwood classics
description: |
    A Libre/Free Real Time Strategy game engine supporting early Westwood classics
networking : yes
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lua-5.1)
    - pkgconfig(mono)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - zenity
rundeps    :
    - libgdiplus
    - lua51
    - mesalib
    - mono
    - openal-soft
    - sdl2-gfx
    - sdl2-image
    - sdl2-mixer
    - sdl2-net
    - sdl2-ttf
    - zenity
setup      : |
    sed -i "s|^VERSION.*$|VERSION = release-$version|" Makefile
build      : |
    %make DEBUG=false dependencies
    %make DEBUG=false version
    %make DEBUG=false
install    : |
    %make_install DEBUG=false prefix=%PREFIX% gameinstalldir=%PREFIX%/share/openra
    %make install-linux-shortcuts DEBUG=false DESTDIR=$installdir prefix=%PREFIX% gameinstalldir=%PREFIX%/share/openra
