name       : openra
version    : '20210321'
release    : 17
source     :
    - https://github.com/OpenRA/OpenRA/releases/download/release-20210321/OpenRA-release-20210321-source.tar.bz2 : cc4c1011210c0395243c198c40294568bc2381ebfbd2f70df11988549307b636
license    : GPL-3.0-or-later
component  : games.strategy
summary    : A Libre/Free Real Time Strategy game engine supporting early Westwood classics
description: |
    A Libre/Free Real Time Strategy game engine supporting early Westwood classics
networking : yes
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lua-5.1)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - mono-msbuild
    - xdg-utils
    - zenity
rundeps    :
    - libgdiplus
    - lua51
    - mesalib
    - mono
    - openal-soft
    - sdl2-gfx
    - sdl2-image
    - sdl2-mixer
    - sdl2-net
    - sdl2-ttf
    - xdg-utils
    - zenity
environment: |
    unset version
    export RUNTIME=mono TARGETPLATFORM=unix-generic
setup      : |
    cert-sync --user /etc/ssl/certs/ca-certificates.crt
    sed -i "s|^VERSION.*$|VERSION = release-%version%|" Makefile
build      : |
    %make
install    : |
    %make_install prefix=/usr gameinstalldir=/usr/share/openra
    %make install-linux-shortcuts DESTDIR=$installdir prefix=/usr gameinstalldir=/usr/share/openra
    %make install-linux-appdata DESTDIR=$installdir prefix=/usr gameinstalldir=/usr/share/openra
