name       : openra
version    : 20160508
release    : 1
source     :
    - https://github.com/OpenRA/OpenRA/archive/release-20160508.tar.gz : 277f9bf9dbe4e9a0a3b66e6207cfc8dfee41e47b070af59229c50238db5e25ef
license    : GPL-3.0
component  : games.strategy
summary    : A Libre/Free Real Time Strategy game engine supporting early Westwood classics
description: |
    A Libre/Free Real Time Strategy game engine supporting early Westwood classics
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lua-5.1)
    - pkgconfig(mono)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - zenity
rundeps    :
    - libgdiplus
    - mono
    - zenity
setup      : |
    sed -i "s|^VERSION.*$|VERSION = release-$version|" Makefile
build      : |
    %make DEBUG=false dependencies
    %make DEBUG=false version
    %make DEBUG=false
install    : |
    %make_install DEBUG=false prefix=/usr gameinstalldir=/usr/share/openra
    %make install-linux-shortcuts DEBUG=false DESTDIR=$installdir prefix=/usr gameinstalldir=/usr/share/openra